### ISSUE TITLE
Revert Servo Configuration Changes from ReactorX Wrist

### ISSUE THREAD

**Issue by nhanson2** [hello-robot/stretch_tool_share#13]
We recently applied the changes to our stretch to add the ReactorX wrist. We'd now like to change the robot back to it's default configuration, but are having trouble getting the original wrist rotation servo to home to the correct position. 

Essentially when we run the calibration script, the wrist rotates beyond the correct stopping point. We've attempted to use Dynamixel Wizard to reset the home position, but it seems like the newly written home value is not respected. Is there a reset script to restore the default arm configuration?

**Comment by hello-binit** [comment]
Hi @nhanson2, reverting to the original configuration should involve updating the User YAML back to what it was before applying the changes from the [ReactorX section](https://github.com/hello-robot/stretch_tool_share/tree/master/tool_share/reactorx_wrist_V1#code). The home position in Dynamixel Wizard doesn't affect where the joints go to. In order to make sure I understand the issue, would you take a video of the issue you're seeing?

**Comment by hello-binit** [comment]
Closing this issue. If you're still facing this issue, please feel free to open a new one.
